services:
  web:
    build:
      context: .
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.shareindia.rule=Host(`shareindiainsurance.com`) || Host(`shareindia.internal.wabisabitech.in`) || Host(`www.shareindiainsurance.com`)'
      - 'traefik.http.routers.shareindia.entrypoints=https'
      - 'traefik.http.routers.shareindia.tls=true'
      - 'traefik.http.services.shareindia.loadbalancer.server.port=3000'
    logging:
      driver: loki
      options:
        loki-url: https://${LOKI_USER}:${LOKI_PASSWORD}@loki.internal.wabisabitech.in/loki/api/v1/push
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1ms
        keep-file: 'true'
        mode: 'non-blocking'
    restart: unless-stopped
    container_name: share-india-website-staging
    environment:
      - NODE_ENV=production
      - PORT=3000

networks:
  proxy:
    external: true
