services:
  web:
    build:
      context: .
    logging:
      driver: loki
      options:
        loki-url: https://${LOKI_USER}:${LOKI_PASSWORD}@loki.internal.wabisabitech.in/loki/api/v1/push
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1ms
        keep-file: 'true'
        mode: 'non-blocking'
    restart: unless-stopped
    container_name: share-india-website-prod
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - '80:3000'
