services:
  web:
    build:
      context: .
    image: siib-website-dev-img
    container_name: siib-website-dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
