name: Production CI/CD Pipeline

on:
  workflow_run:
    workflows: ['Staging Deployment Pipeline'] # must match the `name:` in staging.yml
    types:
      - completed

jobs:
  production-deployment:
    name: Production Deployment
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: TheWabiSabi/action-workflows/.github/workflows/deploy-vps-docker.yml@main
    with:
      DEPLOYMENT_PATH: /home/admin/Share-India-Website
      DEPLOY_URL: http://43.204.38.201
      RUN_ID: ${{ github.run_id }}
      AUTHOR: ${{ github.actor }}
      BRANCH: ${{github.ref_name}}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      REMOTE_HOST: ${{ secrets.REMOTE_HOST_PROD }}
      REMOTE_USER: ${{ secrets.REMOTE_USER_PROD }}

  emergency-rollback-prod:
    name: Emergency Rollback
    needs: production-deployment
    if: ${{ always() && needs.production-deployment.outputs.deployment_status == 'false' }}
    uses: TheWabiSabi/action-workflows/.github/workflows/rollback-docker.yml@main
    with:
      DEPLOYMENT_PATH: /home/ubuntu/projects/wabisabi/Share-India-Website
      PROD_STATUS: ${{ fromJson(needs.production-deployment.outputs.deployment_status) }}
      DEPLOY_ID: ${{ github.run_id }}
      DEPLOY_URL: http://43.204.38.201
      ROLLBACK_TO_COMMIT: ${{ inputs.rollback_to_commit || '' }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      REMOTE_HOST: ${{ secrets.REMOTE_HOST_PROD }}
      REMOTE_USER: ${{ secrets.REMOTE_USER_PROD }}

  # Job 5: Notifications (runs after all other jobs complete)
  notifications-deploy-prod:
    name: Send Notifications
    needs: [production-deployment]
    if: always()
    uses: TheWabiSabi/action-workflows/.github/workflows/notify-deploy.yml@main
    with:
      PROD_STATUS: ${{ fromJson(needs.production-deployment.outputs.deployment_status || 'false') }}
      CALLER_REPO: ${{ github.repository }}
      CALLER_BRANCH: ${{ github.ref_name }}
      CALLER_COMMIT_SHA: ${{ github.sha }}
      AUTHOR: ${{ github.actor }}
      RUN_ID: ${{ github.run_id }}
      LOGS_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      TIMESTAMP: ${{ github.event.head_commit.timestamp }}
    secrets:
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
      SMTP_FROM_EMAIL: ${{ secrets.SMTP_FROM_EMAIL }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

  notifications-rollback-prod:
    name: Send Notifications
    needs: [emergency-rollback-prod]
    if: ${{always() && needs.production-deployment.outputs.deployment_status == 'false'}}
    uses: TheWabiSabi/action-workflows/.github/workflows/notify-rollback.yml@main
    with:
      ROLLBACK_STATUS: ${{ fromJson(needs.emergency-rollback-prod.outputs.rollback_status || 'false') }}
      CALLER_REPO: ${{ github.repository }}
      CALLER_BRANCH: ${{ github.ref_name }}
      CALLER_COMMIT_SHA: ${{ github.sha }}
      AUTHOR: ${{ github.actor }}
      RUN_ID: ${{ github.run_id }}
      LOGS_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      TIMESTAMP: ${{ github.event.head_commit.timestamp }}
    secrets:
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
      SMTP_FROM_EMAIL: ${{ secrets.SMTP_FROM_EMAIL }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
